@startuml IteratorForC#

title IteratorForC#

interface IEnumerator {
  bool MoveNext()
  object Current
}

interface IEnumerable<T> {
  IEnumerator GetEnumerator()
}

IEnumerable .left.> IEnumerator : Create

@enduml